/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: 03b8219b61e4385a521eb8abfa145076)
interface __BaseEnv_Env {
	PLATFORM_DB: D1Database;
	PRODUCT_ANALYTICS: AnalyticsEngineDataset;
	ROOM_CREATION_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	MODEL_RATE_LIMITER: RateLimit;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	TOPIC_ROUTINE_PROVIDER: "offline";
	TOPIC_ESCALATION_PROVIDER: "off";
	MODEL_DAILY_CALL_LIMIT: "25" | "100";
	ROOMS: DurableObjectNamespace<import("./worker").RoomDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "RoomDurableObject";
	}
	interface StagingEnv {
		PLATFORM_DB: D1Database;
		PRODUCT_ANALYTICS: AnalyticsEngineDataset;
		ROOM_CREATION_RATE_LIMITER: RateLimit;
		API_RATE_LIMITER: RateLimit;
		MODEL_RATE_LIMITER: RateLimit;
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
		TOPIC_ROUTINE_PROVIDER: "offline";
		TOPIC_ESCALATION_PROVIDER: "off";
		MODEL_DAILY_CALL_LIMIT: "25";
		ROOMS: DurableObjectNamespace<import("./worker").RoomDurableObject>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TOPIC_ROUTINE_PROVIDER" | "TOPIC_ESCALATION_PROVIDER" | "MODEL_DAILY_CALL_LIMIT">> {}
}
